name: C/C++ CI

on:
  push:
    branches: ["master", "next"]
  pull_request:
    branches: ["master", "next"]

jobs:
  linux_matrix:
    strategy:
      fail-fast: false
      matrix:
        cxxcompiler: [g++,clang++]
        with_experimental: [0,1]
        include:
          - ccompiler: gcc
            cxxcompiler: g++
          - ccompiler: clang
            cxxcompiler: clang++

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Configuring
        run: cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wpedantic -Wshadow -Wconversion' -Dfast_io_ENABLE_TESTS=1 -Dfast_io_ENABLE_BENCHMARKS=1 -Dfast_io_ENABLE_EXAMPLES=1 -Dfast_io_ENABLE_FUZZING=1 -DCMAKE_CXX_COMPILER='${{ matrix.cxxcompiler }}' -DCMAKE_C_COMPILER='${{ matrix.ccompiler }}' -Dfast_io_ENABLE_TESTS_EXPERIMENTAL=${{ matrix.with_experimental }} -Dfast_io_ENABLE_BENCHMARKS_EXPERIMENTAL=${{ matrix.with_experimental }} -Dfast_io_ENABLE_EXAMPLES_EXPERIMENTAL=${{ matrix.with_experimental }} -Dfast_io_ENABLE_FUZZING_EXPERIMENTAL=${{ matrix.with_experimental }}
      - name: CMake build
        run: |
          if [[ "${{ matrix.with_experimental }}" == "1" ]]; then NOT_CONTINUE_AFTER_FAIL='0'; else NOT_CONTINUE_AFTER_FAIL='1'; fi ;
          cmake --build ./build --verbose -j $(nproc) -- -k ${NOT_CONTINUE_AFTER_FAIL}
      - name: CMake test
        run: ctest --test-dir ./build --verbose -j $(nproc)

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Configuring
        run: cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='/EHsc /W3 /WX /sdl' -Dfast_io_ENABLE_TESTS=1 -Dfast_io_ENABLE_BENCHMARKS=1 -Dfast_io_ENABLE_EXAMPLES=1 -Dfast_io_ENABLE_FUZZING=1 -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
      - name: CMake build
        run: |
          cmake --build ./build --verbose -j $(nproc) -- -k 0
      - name: CMake test
        run: ctest --test-dir ./build --verbose -j $(nproc)

  # macos:

  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install ninja-build tool
  #     uses: seanmiddleditch/gha-setup-ninja@v4
  #   - name: cmake
  #     run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
  #   - name: ninja
  #     run: ninja
  #   - name: ninja test
  #     run: ninja test
