name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
    - name: make
      run: make -j
    - name: make test
      run: make test -j

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: cmake
      run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    - name: ninja
      run: ninja
    - name: ninja test
      run: ninja test

  # macos:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: cmake
  #     run: cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On
  #   - name: make
  #     run: make -j
  #   - name: make test
  #     run: make test -j
