name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
    - name: make
      run: make -j
    - name: make test
      run: make test -j

  # macos:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: cmake
  #     run: cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On
  #   - name: make
  #     run: make -j
  #   - name: make test
  #     run: make test -j
